//POST http://localhost:8080/api/guests
//Content-Type: application/json

//Body

//{
    //"name": "Fulano dos Santos",
    //"document": "56478912",
    //"phone": "1234575"
//}

GET http://localhost:8080/api/guests/search?name=Fulano dos Santos
Content-Type: application/json

